version: '3.7'

services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    restart: on-failure
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -q -d stori_db -U admin123']
      timeout: 10s
      interval: 5s
      retries: 10
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: