version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin123
      POSTGRES_DB: stori_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: on-failure
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -q -d stori_db -U admin']
      timeout: 10s
      interval: 5s
      retries: 10
  server:
    image: bank-api
    build: .
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  pgdata: